# - name: Install Elasticsearch
#   apt:
#     name: elasticsearch
#     state: present
#     update_cache: yes

# - name: Configure Elasticsearch Cluster
#   template:
#     src: elasticsearch.yml.j2
#     dest: /etc/elasticsearch/elasticsearch.yml
#   notify: Restart Elasticsearch

# - name: Enable Security
#   lineinfile:
#     path: /etc/elasticsearch/elasticsearch.yml
#     line: "xpack.security.enabled: true"
#   notify: Restart Elasticsearch

# - name: Start Elasticsearch
#   systemd:
#     name: elasticsearch
#     enabled: yes
#     state: started
- name: Install dependencies
  apt:
    name:
      - openjdk-11-jdk
      - apt-transport-https
    state: present

- name: Add Elasticsearch repository
  shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
    echo "deb https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list
  args:
    warn: false
- name: Update package list after adding Elasticsearch repo
  apt:
    update_cache: yes
- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present
  notify: restart elasticsearch

- name: Copy Elasticsearch configuration
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: "0600"
  notify: restart elasticsearch
  # handlers:
  #   - name: Restart Elasticsearch
  #     systemd:
  #       name: elasticsearch
  #       state: restarted